from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class SixRealmsGatesAssets: 


	# Image Rule Assets
	# 六道切换按钮
	I_SIX_GATE_SWITCH = RuleImage(roi_front=(409,295,25,22), roi_back=(409,295,25,22), threshold=0.8, method="Template matching", file="./tasks/SixRealmsGates/res/res_six_gate_switch.png")
	# 选中月之海
	I_SIX_GATE_MOON = RuleImage(roi_front=(593,156,72,42), roi_back=(593,156,72,42), threshold=0.8, method="Template matching", file="./tasks/SixRealmsGates/res/res_six_gate_moon.png")
	# 检查是否为月之海
	I_CHECK_MOON_SEA = RuleImage(roi_front=(349,138,25,21), roi_back=(349,138,25,21), threshold=0.8, method="Template matching", file="./tasks/SixRealmsGates/res/res_check_moon_sea.png")


